# Generated by Django 4.1.7 on 2023-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stockitem_group_remove_stockitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('CARD', 'CARD'), ('NEFT', 'NEFT')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
