# Generated by Django 4.1.7 on 2023-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstockitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
