# Generated by Django 4.1.7 on 2023-03-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderstockitem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_order_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
