# Generated by Django 4.1.7 on 2023-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_change_amount_order_total_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('INVALID', 'INVALID')], max_length=255),
        ),
    ]
